[package]
name = "orca"
version = "0.2.0"
authors = ["Benny A <virusdownloader7@gmail.com>"]
description = "A Reddit API client for Rust"
repository = "https://github.com/IntrepidPig/orca"
license = "MPL-2.0"

[dependencies]
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.7"
failure = "0.1"
failure_derive = "0.1"
open = "1.2"
tiny_http = "0.5"
url = "1.6"
rand = "0.3"
